### ISSUE TITLE
Question about services in the command handlers

### ISSUE THREAD

**Issue by shesupplypi** [dlydiard/ddd-cqrs-es-aws-sam#37]
Hi,

Thanks for publishing this- your repo has been very helpful for understanding CQRS and event sourcing.  I am wondering why you chose to create a service class call the repository from the service class, rather than directly from the command handler?  I was trying to find more information about services in command handlers but did not find much.  Thanks!

**Comment by shesupplypi** [comment]
Also, why are you using DTOs then turning them into commands inside of the controller? Why not just directly create the command there from the event body?

**Comment by dlydiard** [comment]
I'm a bit busy these days, so I'm going from memory... I believe the answer to both questions are that the patterns were heavily inspired by NestJS and that framework is very opinionated. 

So it all comes down to separate of concerns:

- CommandHandler to delegate
- Service to process domain logic (business rules)
- Repository to manage persistence

And this is all (de)coupled with dependency Injection. I think in the code examples it's not very obvious since the services contain very little to no business logic, so it looks like the separation is unnecessary.

As for the DTOs, I believe they have class-validator annotations on them to validate the incoming request. So in a purest sense, the Command shouldn't know anything about a request object since request objects are a controller concern. Although they (request and command params) happen to use the same object, they don't necessarily have to.  

Hope that helps, and thank you for visiting this project!

**Comment by shesupplypi** [comment]
That was helpful, makes sense.  Thanks!
